development:
  adapter: postgresql
  database: nettsundere_web_development
  username: postgres
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: nettsundere_web_test
  username: postgres
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: nettsundere_web_production
  username: postgres
  pool: 5
  timeout: 5000
